apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  OPENWEATHER_API_KEY: <base64_encoded_openweather_api_key>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pawa-challenge-backend
  labels:
    app: pawa-challenge-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pawa-challenge-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: pawa-challenge-backend
    spec:
      containers:
      - name: pawa-challenge-backend
        image: nexttechglobe/pawa-challenge-backend:lastest
        ports:
        - containerPort: 8000
        env:
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: OPENWEATHER_API_KEY
      


---
apiVersion: v1
kind: Service
metadata:
  name: pawa-challenge-backend
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: pawa-challenge-backend