name: Deploy Frontend
on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          echo "Tests passed"
    #   - name: Cypress run
    #     uses: cypress-io/github-action@v6
    #     with:
    #       browser: chrome
    #       record: true
    #       start: npm run dev
    #       wait-on: 'http://localhost:3000'

    #     env:
    #       CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
    #       CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    #       CYPRESS_ENV: 'production'
    #       CYPRESS_CI: 'true'
    #       CYPRESS_VIDEO: 'true'
    #       CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
    #       CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}


  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:
      - name: Generate tag
        id: tag
        run: 
          echo "TAG=$(date +'%y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV  
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pawa-challenge-frontend:latest
          file: ./weather-frontend/Dockerfile
          

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
  
    - name: Update deployment file
      run: |
        sed -i "s|<IMAGE_NAME>:<TAG>|nexttechglobe/pawa-challenge-frontend:latest|g" $GITHUB_WORKSPACE/config/frontend-deployment.yaml
        cat $GITHUB_WORKSPACE/config/frontend-deployment.yaml
    - name: Image path
      run : |
          echo  ${{ secrets.DOCKER_USERNAME }}/pawa-challenge-frontend:latest

  
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: >-
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{secrets.CLUSTER_NAME }}
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        kubectl apply -f $GITHUB_WORKSPACE/config/frontend-deployment.yaml
    - name: Verify deployment
      run: kubectl rollout status deployment/pawa-challenge-frontend