

name: Deploy Backend
on:
  workflow_dispatch:
  push:
    branches:
      main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: yarn install

    - name: Run tests
      run: echo "Tests passed"


  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/pawa-challenge-backend:latest
          file: ./weather-backend/Dockerfile
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@main
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
    - name: Get base64 encoded secrets
      id: secrets
      run: |
        echo "::set-output name=openweather_api_key::$(echo -n ${{ secrets.OPENWEATHER_API_KEY }} | base64)"
  
  
    - name: Update deployment file
      run: |
        sed -i "s|<base64_encoded_openweather_api_key>|$(echo -n ${{ steps.secrets.outputs.openweather_api_key }})|" $GITHUB_WORKSPACE/config/backend-deployment.yaml
  
      
    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: >-
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{secrets.CLUSTER_NAME }}
    - name: Deploy to DigitalOcean Kubernetes
      run: |
        # kubectl delete -f $GITHUB_WORKSPACE/config/backend-deployment.yaml
        kubectl apply -f $GITHUB_WORKSPACE/config/backend-deployment.yaml
    - name: Verify deployment
      run: kubectl rollout status deployment/pawa-challenge-backend